INSERT INTO OWNER(OWNER_ID, FIRST_NAME, LAST_NAME) VALUES(1, 'Joe', 'Doe');
INSERT INTO OWNER(OWNER_ID, FIRST_NAME, LAST_NAME)  VALUES(2, 'Albert', 'Dickson');
INSERT INTO OWNER(OWNER_ID, FIRST_NAME, LAST_NAME)  VALUES(3, 'Javito', 'Larsson');
INSERT INTO OWNER(OWNER_ID, FIRST_NAME, LAST_NAME)  VALUES(4, 'Michel', 'Angelo');


INSERT INTO CAR(MODEL_YEAR, PRICE, CAR_ID, OWNER_ID, BRAND, COLOR, MODEL, REGISTRATION_NUMBER)
VALUES(2015, 10000, 1, 2, 'FIAT', 'Red', '1', 'gbc521');
INSERT INTO CAR(MODEL_YEAR, PRICE, CAR_ID, OWNER_ID, BRAND, COLOR, MODEL, REGISTRATION_NUMBER)
VALUES(2020, 20000, 2, 1, 'FORD', 'White', 'other', 'dhc121');
INSERT INTO CAR(MODEL_YEAR, PRICE, CAR_ID, OWNER_ID, BRAND, COLOR, MODEL, REGISTRATION_NUMBER)
VALUES(2015, 11000, 3, 3, 'KIA', 'Blue', 'ffdc', 'ajc223');
INSERT INTO CAR(MODEL_YEAR, PRICE, CAR_ID, OWNER_ID, BRAND, COLOR, MODEL, REGISTRATION_NUMBER)
VALUES(2019, 12400, 4, 4, 'FERRARI', 'Green', 'hdx', 'add321');
INSERT INTO CAR(MODEL_YEAR, PRICE, CAR_ID, OWNER_ID, BRAND, COLOR, MODEL, REGISTRATION_NUMBER)
VALUES(2021, 15500, 5, 1, 'VOLVO', 'Yellow', 'hj4', 'adj341');
INSERT INTO CAR(MODEL_YEAR, PRICE, CAR_ID, OWNER_ID, BRAND, COLOR, MODEL, REGISTRATION_NUMBER)
VALUES(2014, 15550, 6, 4, 'FORD', 'Red', '4fc', 'abh367');
INSERT INTO CAR(MODEL_YEAR, PRICE, CAR_ID, OWNER_ID, BRAND, COLOR, MODEL, REGISTRATION_NUMBER)
VALUES(2016, 16000, 7, 3, 'SUZUKI', 'White', 'hdw', 'sde143');
